linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - goimports
    - goconst
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gocritic:
    disabled-checks:
      - ifElseChain
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  dogsled:
    max-blank-identifiers: 3
  goimports:
    local-prefixes: github.com/tsocial/telco_gateway_xlaxiata
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
          - cloud.google.com

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - goconst
        - gosec

run:
  timeout: 10m