CREATE TABLE IF NOT EXISTS `my_books`.`books`
(
    `id` BIGINT(20) NOT NULL AUTO INCREMENT,
    `name` VARCHAR(255) NOT NULL DEFAULT '',
    `author` VARCHAR(127) NOT NULL DEFAULT '',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;