CREATE TABLE IF NOT EXISTS `my_books`.`books`
(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL DEFAULT '',
    `author` VARCHAR(127) NOT NULL DEFAULT '',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
    ) ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE IF NOT EXISTS `my_books`.`reads`
(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `book_id` BIGINT(20) NOT NULL,
    `source` VARCHAR(127) NOT NULL DEFAULT '',
    `language` VARCHAR(31) NOT NULL DEFAULT '',
    `finished_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;